Post/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('view/<int:id>',views.view_post,name="view_post"),
	path('create_post_ajax/',views.create_post_ajax,name="create_post_ajax"),
	path('create_comment_ajax/',views.create_comment_ajax,name="create_comment_ajax"),
	path('like/',views.like_post,name="like_post"),
	path('unlike/',views.unlike_post,name="unlike_post"),
]

SocialApp/urls.py
from django.contrib import admin
from django.urls import path, include
from Post import views
from django.conf.urls.static import static
from django.conf import settings
from search import views as search_views
from user import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('post/',include(('Post.urls','Post'),namespace='post')),
    path('user/',include(('user.urls','user'),namespace='user')),
    path('search/',search_views.search, name='search'),
    path('<str:username>/',search_views.view_profile,name='view_profile'),
    path('<str:username>/replies/',user_views.view_replies,name="view_replies"),
    path('<str:username>/likes/',user_views.view_likes,name='view_likes'),
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('login/',views.loginUser,name = "login"),
    path('register/',views.register,name = "register"),
    path('logout/',views.logoutUser,name = "logout"),
    path('edit/<str:username>',views.change_user,name="user-edit"),
    path('view/<str:username>',views.view_user,name="user-view"),
    path('set-perm/',views.view_permission,name = "set-perm"),
    path('add-delete-perm/<int:pk>',views.change_permission,name='add-delete-perm'),
    path('add-group/',views.add_group,name='add-group'),
    path('change-group/',views.change_group,name='change-group'),
    path('remove-group/',views.remove_group,name='remove-group'),
    path('show-group-members/<str:name>',views.show_group_members,name='show-group-members'),
    path('edit-user/<str:username>',views.edit_user,name='edit-user'),
    path('view-other-user/<str:username>',views.view_other_user,name='view-other-user')
    
]

Post/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField

# Create your models here.
def upload_to(instance,filename):
	username = instance.post.user.username
	return '%s/%s/%s'%('PostsFiles',username,filename)

class Location(models.Model):
	
	city = models.CharField(max_length = 30, blank=True, null=True, default='')
	country = models.CharField(max_length = 60, blank=True, null=True, default='')
	coordinates = JSONField(blank=True, null=True,default=dict)

	def __str__(self):
		return '/'.join([self.city,self.country])

class CommonField(models.Model):
	statement = models.TextField(null=False, blank=False)
	created_date = models.DateTimeField(auto_now_add = True)
	updated = models.DateTimeField(auto_now = True)

	class Meta:
		abstract = True

class Post(CommonField):
	user = models.ForeignKey('user.User', on_delete=models.CASCADE, related_name = 'post')
	location = models.ForeignKey(Location, blank=True, null=True, on_delete=models.SET_NULL,related_name='post')

	class Meta:
		ordering = ['-created_date']


class Comment(CommonField):
	user = models.ForeignKey('user.User', on_delete=models.CASCADE, related_name = 'comment')
	post = models.ForeignKey(to=Post, on_delete=models.CASCADE,related_name="comment")

	class Meta:
		ordering = ['created_date']


class File(models.Model):
	post = models.ForeignKey(to=Post, on_delete=models.CASCADE,related_name='file')
	file = models.FileField(upload_to=upload_to, null=True, blank=True)

class Tag(models.Model):
	title = models.CharField(max_length=120, unique = True)

	def __str__(self):
		return self.title
		
class TagPost(models.Model):
	post = models.ForeignKey(to=Post, on_delete=models.CASCADE, related_name='tag')
	tag = models.ForeignKey(to=Tag, on_delete=models.CASCADE, related_name='post')
	title = models.CharField(max_length=120, null = False, blank = False)

	def __str__(self):
		return self.tag.title

class Like(models.Model):
	user = models.ForeignKey('user.User',on_delete=models.CASCADE,related_name = 'likes')
	post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='likes')
	created_date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.user.username +" Liked "+ str(self.post.id)

	class Meta:
		constraints = [ models.UniqueConstraint(fields=['user','post'],  name="unique_like")]

		ordering = ["-created_date"]

search/models.py
from django.db import models

# Create your models here.

Post/forms.py
from django import forms
from .models import Post, Comment, File, Tag


class PostForm(forms.ModelForm):

	class Meta:
		model = Post
		fields = ['statement','location']

class CommentForm(forms.ModelForm):

	class Meta:
		model = Comment
		fields = ['statement']

	def clean_statement(self):
		statement = self.cleaned_data['statement']
		if len(statement) == 0:
			raise forms.ValidationError("Comment cannot be left blank.")
		return statement

class FileForm(forms.ModelForm):

	class Meta:
		model = File
		fields = ['file']

	def __init__(self, *args, **kwargs):
		super(FileForm, self).__init__(*args,**kwargs)
		self.fields['file'].widget.attrs['multiple']

class TagForm:

	def clean_title(title):
		tag_model = Tag.objects.values_list('title', flat=True)
		#Tag.objects.values('title') yaptığımda sadece title değerlerini dict nesnesi olarak bana dönüyor
		#values_list 'i ise flat=True olmadan kullanırsam liste içerisinde her bir değeri tuple olarak veriyor.
		#values_list'i flat=True olarak kullanırsam tam istediğim gibi değerleri liste içerisinde veriyor.
		
		if title.startswith('#'):
			title = title.replace('#','',1)


		if title in tag_model:
			title = Tag.objects.get(title = title)
			return title
		else:
			new_tag = Tag()
			new_tag.title = title
			new_tag.save()
			return new_tag

Post/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, reverse, get_object_or_404, HttpResponse
from .models import Post, File, Tag, Comment, TagPost, Like, Location
from .forms import PostForm, FileForm, TagForm, CommentForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from user.models import User
from django.http import JsonResponse
from django.core.files.base import ContentFile
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db import IntegrityError
import json
import base64
import os
from django.db.models import Q
import geoip2.database
from geoip2.errors import AddressNotFoundError
# Create your views here.

@login_required(login_url = 'user:login')
def index(request):
	posts = Post.objects.select_related('user').filter(Q(user__followers__user_id = request.user.id)|Q(user = request.user.id))
	page = request.GET.get('page',1)
	paginator = Paginator(posts,10)
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)
	return render(request,'posts.html',{'posts':posts})

@login_required(login_url='user:login')
def view_post(request,id):
	post = Post.objects.select_related('user').get(id = id)
	return render(request,'view_post.html',{'post':post})

@login_required(login_url = 'user:login')
def create_post_ajax(request):
	if request.method == "POST" and request.is_ajax():
		if not request.user.is_authenticated:
			return HttpResponseRedirect(reverse('user:login'))

		if request.POST.get('statement'):
			reader = geoip2.database.Reader('GeoLite2-City.mmdb')
			try:
				response = reader.city(request.META.get('REMOTE_ADDR'))

				location = Location.objects.create(city = response.city.name, country = response.country.name, coordinates = {'latitude':response.location.latitude,'longitude':response.location.longitude})

			except AddressNotFoundError:
				location = None

			post = Post.objects.create(user = request.user, statement = request.POST.get('statement'), location = location)
		else:
			return JsonResponse({"success":False}, status=406)

		if request.POST.get('files'):
			files = json.loads(request.POST.get('files'))['files']

			for file in files:
				
				file_data = file
				format, filestr = file_data.split(';base64,')
				ext = format.split('/')[-1]
				data = ContentFile(base64.b64decode(filestr), name='temp.'+ext)
				file = File.objects.create(post = post, file = data)
				
		if request.POST.get('tags'):
			tags = json.loads(request.POST.get('tags'))['tags']

			for tag in tags:
				TagPost.objects.create(title=tag,post = post, tag = TagForm.clean_title(title=tag))

		return JsonResponse({"success":True}, status=200)
	return JsonResponse({"success":False}, status=400)

@login_required(login_url = 'user:login')
def create_comment_ajax(request):
	if request.method == "POST" and request.is_ajax():
		post_id = request.POST.get('post_id')
		post_id = int(post_id)
		post = Post.objects.get(id = post_id)

		if request.POST.get('statement'):
			Comment.objects.create(post = post, statement = request.POST.get('statement'), user = request.user)
		else:
			return JsonResponse({"success":False}, status=406)
		return JsonResponse({"success":True}, status=200)
	return JsonResponse({"success":False}, status=400)

@login_required(login_url = 'user:login')
def like_post(request):
	if request.is_ajax():
		post_id = int(request.GET.get('post_id'))
		post = Post.objects.get(id = post_id)
		authUser = request.user
		try:
			Like.objects.create(user = authUser, post = post)
		except IntegrityError:
			return JsonResponse({"success":False}, status=406)
		return JsonResponse({"success":True}, status=200)
	else:
		return JsonResponse({"success":False}, status=400)

@login_required(login_url = "user:login")
def unlike_post(request):
	if request.is_ajax():
		post_id = int(request.GET.get('post_id'))
		post = Post.objects.get(id = post_id)
		authUser = request.user
		like = Like.objects.get(post=post, user=authUser)
		like.delete()
		return JsonResponse({"success":True}, status = 200)
	return JsonResponse({"success":False}, status=400)



#https://stackoverflow.com/questions/39576174/save-base64-image-in-django-file-field
#buradan base64'ü fotoyu çevirmeyi yap çünkü FileReader() ile js kullanarak yüklenen fotoyu ekranda göstermek için bize fotonun base64 kodunu veriyor.
#Yapıldı !!!




#https://stackoverflow.com/questions/58552487/how-to-calculate-video-length-and-thumbnail-of-video-in-django
#video uzunluğunu bu linkteki yöntem ile kontrol edebilirim fakat orada söylenenin aksine
#VideoClipFile değil VideoFileClip kullanmalıyım çünkü diğeri yok.


#Infinite scroll için kaynaklar:
#https://dev.to/coderasha/infinite-scroll-with-django-d0a
#https://github.com/raszidzie/infinite-scroll/blob/master/templates/posts.html
#https://simpleisbetterthancomplex.com/tutorial/2017/03/13/how-to-create-infinite-scroll-with-django.html
#infinite scroll için js kodunu ilk linkten aldım ve daha sonra infinite-container class'lı divi diğer col'lu divlerden ayırdım
#o şekilde düzgünce çalıştı.

search/views.py
from django.shortcuts import render, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from search.documents import PostDocument, UserDocument, TagDocument
from django.contrib import messages
from user.models import User
# Create your views here.

def search(request):

	q = request.GET.get('q')
	searchq = request.GET.get('searchq')
	if q:
		if searchq == 'userq':
			users = UserDocument.search().query("match",username=q)

			if (len(list(users)) == 0):
				messages.warning(request,'Results not found','danger')

			return render(request,'search_user.html',{'users':users,'searchValue':q})

		if searchq == 'tagq':
			tags = TagDocument.search().query("match",title=q)

			if (len(list(tags)) == 0):
				messages.warning(request,'Results not found','danger')

			return render(request,'search_tag.html',{'tags':tags,'searchValue':q})
			
		posts = PostDocument.search().query("match", statement=q)
		if (len(list(posts)) == 0):
			messages.warning(request,'Results not found!','danger')
		#posts = posts.to_queryset()
	else:
		posts = ''
	return render(request, 'search.html',{'posts':posts,'searchValue' : q})

def view_profile(request,username):
	user = UserDocument.search().query("match",username=username)

	try:
		user = list(user)[0]
	except IndexError:
		return HttpResponse('<h3>User not found</h3>')
	posts = user.post

	page = request.GET.get('page',1)
	paginator = Paginator(posts,10)
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)

	return render(request, 'user_profile.html',{'users':user,'posts':posts})

	#user'da relatedobject manager is not iterable hatası alıyorum .to_queryset() bunu kullandığımda.
	#sanırım bunun nedeni userdocument içerisinde objectfield çağırdığımdan kaynaklanıyor.


#https://www.youtube.com/watch?v=cXYVE28igkE
#to_queryset yaparak normal django querysetine çeviriyorum yoksa user bilgisine vs ulaşamıyorum.
#onlara nasıl ulaşabileceğimi bulamadım. BULDUM, user da post'u, post'da file'ı çekebiliyorum.

templates/edit_profile.html
{% extends 'main_page.html' %}
{% load widget_tweaks %}
{% block posts %}


<div class="row" style="width:25%;color:white;margin-left:25%;margin-bottom: 20px;">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <img src="{{request.user.get_image_or_default}}" class="rounded-circle z-depth-2" data-holder-rendered="true" id="show-avatar"> <br>
        
        <label class="login-input-labels">Avatar</label>{% render_field form.avatar  %} <br>
        <labe class="login-input-labels"l>Username</label>{% render_field form.username %} <br>
        <label class="login-input-labels">Email</label>{% render_field form.email %} <br>
        <label class="login-input-labels">Info</label>{% render_field form.info %} <br>
        <label class="login-input-labels">Birthday</label><!--{% render_field form.birthday %}--><input type="date" name="birthday" id="id_birthday" class="form-control" value='{{request.user.birthday|date:"Y-m-d"}}'> <br>
        <label class="login-input-labels">Web Page</label>{% render_field form.web_page %} <br>
        <label class="login-input-labels">Password</label>{% render_field form.password %} <br>
        <label class="login-input-labels">Confirm</label>{% render_field form.confirm %} <br>
        <input type="submit" class="btn btn-outline-primary" value="Register" id="id_register">
    </form>
</div>

<style>
#id_avatar
{
display: block !important;
}
</style> 

{% endblock %}

templates/input.html
<div class="row">

  <div class="col-lg-1 col-md-0 col-sm-0 col-xs-0"></div>
  <div class="col-lg-2 col-md-2 col-sm-1 col-xs-0"></div>
  <div class="col-lg-6 col-md-8 col-sm-10 col-xs-12">
    {% include 'popDiv.html' %}
    <div class="content">

      <form method="post" enctype="multipart/form-data" id="post_form" >
      {% csrf_token %}
      <input type="hidden" name="files" id="files_id" value="">
      <textarea  rows="2" name="statement" id="id_statement" placeholder="What's up!"></textarea>

      <input type="hidden" name="tags" id="tags">
      <label class="custom_file_upload"><i class="fas fa-upload file_upload"></i><input type="file" id="file_id" onchange="readImage(this)" accept=".jpg, .jpeg, .png, .mp4, .wmv, .avi"></label>
      <label class="input_value" id="fileLabel"></label>
      <button class="btn-sm btn-outline-primary float-right" onclick="send_tags(this)">Submit</button>
      <div class="thumbnail" id="thumbnail_id"></div>
      </form>
      
    </div>

    </div>
  <div class="col-lg-2 col-md-2 col-sm-1 col-xs-0"></div>
  <div class="col-lg-1 col-md-0 col-sm-0 col-xs-0"></div>
</div>

templates/login.html
{% extends 'main_page.html' %}
{% block posts %}


<div class="row" style="color:white;margin-left:25%;">
    <form method="POST" class="input-form">
        {% csrf_token %}
        {% for field in form %}
            <label class="login-input-labels">{{field.label}}</label> {{field}} <br>
        {% endfor %}
        <input type="submit" class="btn btn-outline-primary" value="Login" id="id_register">
        <p style="margin-top:5px;">
        If you don't have an account <a href="{% url 'user:register' %}">REGISTER</a></p>
    </form>
    
</div>

{% endblock %}

templates/main_page.html
{% load static %}
{% load check_file_type %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="{% static 'css/site.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/png" href="/media/favicon.png"/>
    <link href="{% static 'fontawesome-free-5.13.0-web/css/all.css' %}" rel="stylesheet">
    <link href="https://vjs.zencdn.net/7.10.2/video-js.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <title>SOCIAL MEDIA</title>
  </head>
  <body>

      {% include 'navbar.html'%}
      
      {% include 'messages.html' %}
      {% block posts %}

      {% endblock %}


    <style>
    body{
      margin: 0;
    font-family: Arial;
    font-size: 17px;
    /*background: rgba(10,10,10,0.8);*/
    background: #0d1117;
    }
        
    </style>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!--<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>-->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://vjs.zencdn.net/7.10.2/video.min.js"></script>
    <!--<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
-->
  {% block script %}
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/infinite.min.js' %}"></script>
    <script src="{% static 'js/controls.js' %}"></script>
  {% endblock %}
  </body>
  <script>
  
  </script>
</html>

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible offset-3" id="alert" role="alert" align="center" style="width:50%;margin-top:10px;">
            <button onclick="hideDiv(this)" type="button"  class="close" id="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
{% load bootstrapHelper %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/"><img src="/media/Django.png"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {{request.path|isActive:'/'}}">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link {{request.path|isActive:request.user.pathName}}" href="{% url 'view_profile' username=request.user.username %}">Profile</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          User Settings
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Settings</a>
          <a class="dropdown-item" href="#">Null</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'user:logout' %}">Logout</a>
        </div>
      </li>
      {% else %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sign In or Sign Up
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'user:login' %}">Login</a>
          <a class="dropdown-item" href="{% url 'user:register' %}">Register</a>
        </div>
      </li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" id="id_search_form" action="/search/" method="get">
      <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search" value="{{searchValue}}">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

templates/popDiv.html
<div class="row">
<div class="popDiv" id="popDiv_id" align="center">

	<div class="popDiv-content" id="popDiv-content-id">
		<form method="post" enctype="multipart/form-data" id="comment_form">
			{% csrf_token %}
			<input type="hidden" name="files" id="comment_files_id" value="">
			<textarea  rows="2" name="statement" id="id_comment_statement" placeholder="What's up!"></textarea>

			<input type="hidden" name="post_id" id="post_id_value">
			<label class="input_value" id="fileLabel"></label>
            <button class="btn-sm btn-outline-primary float-right">Submit</button>
            <div></div>
		</form>

	</div>

</div>
</div>

<script>


</script>

templates/view_post.html
{% extends 'main_page.html' %}
{% load check_file_type %}
{% load humanize %}
{% block posts %}

<div class="row" id="invisible_comment" align="center">
    <div class="col-lg-6 col-md-8 col-sm-10 col-xs-12"> 
      <div class="content">
  
        <form method="post" enctype="multipart/form-data" id="comment_form" >
        {% csrf_token %}
        <input type="hidden" name="files" id="files_id" value="">
        <textarea  rows="2" name="statement" id="id_statement" placeholder="Enter comment!"></textarea>

        <input type="hidden" name="post_id" id="post_id_value" value="{{post.id}}">
        
        <label class="input_value" id="fileLabel"></label>
        <button class="btn-sm btn-outline-primary float-right" onclick="hideComment(this)">Submit</button>
        <div class="thumbnail" id="thumbnail_id"></div>
        </form>
        
      </div>

    </div>
  </div>

<div class="row">
      <div class="col-lg-1 col-md-0 col-sm-0 col-xs-0"></div>
      <div class="col-lg-2 col-md-2 col-sm-1 col-xs-0"></div>
      <div class="col-lg-6 col-md-8 col-sm-10 col-xs-12"> 
        
        <div class="content">
          <div class="row">
            <div class="col-sm-12"><img src="{{post.user.get_image_or_default}}" class="rounded-circle z-depth-2" data-holder-rendered="true" style="position:relative;height: 60px; width:60px; float:left;">
            
              <a href="#{{post.id}}_id" id="{{post.id}}_id" style="color:white;text-decoration: none;font-size: bold;margin-left:5px;">{{post.user}}</a>
            </div>
          </div>
          <hr>
          <div class="row">
          <div class="col-12"> <p id="{{post.id}}">{{post.statement}}</p> <br>
            {% if post.file.get %}
            {% if not post.file.get.file.path|image_or_video %}
      <div align="center">
        <video
          id="my-video"
          class="video-js"
          controls
          preload="auto"
          data-setup="{}">
          <source src="{{post.file.get.file.url}}" type="video/mp4" />
          <p class="vjs-no-js">
            To view this video please enable JavaScript, and consider upgrading to a
            web browser that
            <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
          </p>
        </video>
      </div>
            {% else %}
            <img src="{{post.file.get.file.url}}" id="my-video">
            {% endif %}
          {% endif %}
          <div class="status" id="status_id">

            <i class="far fa-comment popBtn" id="{{post.id}}" onclick="showComment()"></i><label style="margin-left:3px;">{{post.comment.count}}</label>
            {% if post.id in request.user.get_likes_list %}
          <label class="custom_file_upload">
            <i id="red-heart-{{post.id}}" class="far fa-heart popBtnLike" style="color:red;"></i>
            <input class="likePostSubmit" id="unlike-{{post.id}}" onclick="handleLike(this)" value="{{post.id}}">
            <label id="like-count-{{post.id}}" style="margin-left:3px;" >{{post.likes.count}}</label>
          </label>
          {% else %}
          <label class="custom_file_upload">
            <i id="white-heart-{{post.id}}" class="far fa-heart popBtnLike" style="color:white;"></i>
            <input class="likePostSubmit" id="like-{{post.id}}" onclick="handleLike(this)" value="{{post.id}}">
            <label id="like-count-{{post.id}}" style="margin-left:3px;">{{post.likes.count}}</label>
          </label>
          {% endif %}

          </div>
          </div>
          </div>
        </div>

    </div>
    <div class="col-lg-2 col-md-2 col-sm-1 col-xs-0"></div>
    <div class="col-lg-1 col-md-0 col-sm-0 col-xs-0"></div>
  </div>
<div class="vertical-line" style="margin-left:50%;"></div>
  <div class="row">
      <div class="col-lg-1 col-md-0 col-sm-0 col-xs-0"></div>
      <div class="col-lg-2 col-md-2 col-sm-1 col-xs-0"></div>
      <div class="col-lg-6 col-md-8 col-sm-10 col-xs-12"> 
        {% for comment in post.comment.union %}
        <div class="content">
          <div class="row">
            <div class="col-sm-12"><img src="{{comment.user.get_image_or_default}}" class="rounded-circle z-depth-2" data-holder-rendered="true" style="position:relative;height: 50px; float:left;">
            
              <a href="#{{comment.id}}_id" id="{{comment.id}}_id" style="color:white;text-decoration: none;font-size: bold;margin-left:5px;">{{comment.user}}</a> <small style="color:gray;"> | {{post.created_date|naturaltime}}</small>
            </div>
          </div>
          <hr>
          <div class="row">
          <div class="col-12"> <p id="{{post.id}}">{{comment.statement}}</p> <br>
            
          </div>
          </div>
        </div>
        {% endfor %}

    </div>
    <div class="col-lg-2 col-md-2 col-sm-1 col-xs-0"></div>
    <div class="col-lg-1 col-md-0 col-sm-0 col-xs-0"></div>
  </div>

{% endblock %}